package com.creatoros.auth.service;

import com.creatoros.auth.dto.AuthResponse;
import com.creatoros.auth.dto.LoginRequest;
import com.creatoros.auth.dto.RegisterRequest;
import com.creatoros.auth.entity.User;
import com.creatoros.auth.repository.UserRepository;
import com.creatoros.common.exception.ConflictException;
import com.creatoros.common.security.JwtUtil;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Lazy;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * AuthService — handles user registration and login.
 *
 * Why does this implement UserDetailsService?
 *   Spring Security's AuthenticationManager needs to load users by username
 *   to verify credentials. "Username" in our system = email address.
 *   By implementing UserDetailsService and registering it here,
 *   Spring auto-wires it into the DaoAuthenticationProvider, which is
 *   used by authManager.authenticate(...) during login.
 *
 *   The interface requires one method:
 *     UserDetails loadUserByUsername(String username)
 *   We implement it to load a User by email from the DB.
 *
 * ── Register flow ─────────────────────────────────────────────────────────────
 *   1. Check if email already exists → ConflictException if so
 *   2. BCrypt hash the password
 *   3. Build and save User entity
 *   4. Generate JWT for the new user
 *   5. Return AuthResponse (token + user info)
 *
 * ── Login flow ────────────────────────────────────────────────────────────────
 *   1. Call authManager.authenticate(email, rawPassword)
 *      → DaoAuthenticationProvider loads user by email (via loadUserByUsername)
 *      → BCryptPasswordEncoder.matches(rawPassword, storedHash)
 *      → throws BadCredentialsException if no match
 *   2. If auth succeeds, load the full User entity
 *   3. Generate JWT
 *   4. Return AuthResponse
 *
 * ── @Transactional ───────────────────────────────────────────────────────────
 *   Wraps the method in a database transaction. If anything fails midway
 *   (e.g. DB error after saving the user but before something else),
 *   the whole operation rolls back. Prevents partial data.
 */
@Slf4j
@Service
public class AuthService implements UserDetailsService {

    private final UserRepository      userRepository;
    private final PasswordEncoder     passwordEncoder;
    private final JwtUtil             jwtUtil;

    // @Lazy breaks the circular dependency:
    // AuthService needs AuthenticationManager
    // AuthenticationManager needs AuthService (as UserDetailsService)
    // @Lazy tells Spring: create a proxy now, inject the real bean only when first called
    private final AuthenticationManager authenticationManager;

    public AuthService(UserRepository userRepository,
                       PasswordEncoder passwordEncoder,
                       JwtUtil jwtUtil,
                       @Lazy AuthenticationManager authenticationManager) {
        this.userRepository      = userRepository;
        this.passwordEncoder     = passwordEncoder;
        this.jwtUtil             = jwtUtil;
        this.authenticationManager = authenticationManager;
    }

    // ── Register ─────────────────────────────────────────────────────────────

    @Transactional
    public AuthResponse register(RegisterRequest request) {
        // 1. Guard: email uniqueness
        if (userRepository.existsByEmail(request.email())) {
            throw new ConflictException("Email is already registered: " + request.email());
        }

        // 2. Hash password — BCrypt is intentionally slow (work factor = 10 rounds)
        //    to make brute-force attacks expensive even if the DB is compromised
        String hash = passwordEncoder.encode(request.password());

        // 3. Build and persist the User entity
        //    @Builder lets us set only the fields we want — id, createdAt, updatedAt
        //    are auto-generated by Postgres / Hibernate
        User user = User.builder()
                .email(request.email().toLowerCase().trim())  // normalise email
                .passwordHash(hash)
                .name(request.name().trim())
                .build();

        User saved = userRepository.save(user);
        log.info("New user registered: {} ({})", saved.getId(), saved.getEmail());

        // 4. Generate JWT and return
        String token = jwtUtil.generateToken(saved.getId());
        return new AuthResponse(token, saved.getId(), saved.getName(), saved.getEmail());
    }

    // ── Login ─────────────────────────────────────────────────────────────────

    public AuthResponse login(LoginRequest request) {
        // 1. Delegate to Spring Security's auth machinery.
        //    This calls loadUserByUsername(email) → BCrypt.matches(rawPw, hash)
        //    Throws BadCredentialsException on failure (caught by GlobalExceptionHandler → 401)
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(
                        request.email().toLowerCase().trim(),
                        request.password()
                )
        );

        // 2. If we reach here, credentials were valid — load the full User
        User user = userRepository.findByEmail(request.email().toLowerCase().trim())
                .orElseThrow(() -> new RuntimeException("User disappeared after auth — should never happen"));

        log.info("User logged in: {} ({})", user.getId(), user.getEmail());

        // 3. Generate JWT and return
        String token = jwtUtil.generateToken(user.getId());
        return new AuthResponse(token, user.getId(), user.getName(), user.getEmail());
    }

    // ── UserDetailsService impl ───────────────────────────────────────────────

    /**
     * Called by Spring Security's DaoAuthenticationProvider during authenticate().
     * Loads the user by email (which we use as the "username").
     * Returns a Spring UserDetails object wrapping our User entity.
     */
    @Override
    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
        User user = userRepository.findByEmail(email.toLowerCase().trim())
                .orElseThrow(() -> new UsernameNotFoundException("User not found: " + email));

        // Spring Security's built-in User builder (different from our User entity!)
        // Wraps the user into the UserDetails interface Spring Security needs.
        return org.springframework.security.core.userdetails.User.builder()
                .username(user.getEmail())
                .password(user.getPasswordHash())  // the BCrypt hash — Spring will compare
                .roles("USER")
                .build();
    }
}
